version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      - PHP_ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=enabled=1  mode=debug client_host=172.17.0.1 client_port=9003
    ports:
      - '80:80'

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=BookCollection
      - MYSQL_USER=biblio
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'